### ISSUE TITLE
issue installing version 0.5.4 in my environment.

### ISSUE THREAD

**Issue by dash-hugo-vanthournhout** [andrix/python-snappy#102]
Hi!
Thank you for maintaining this library for everyone !

I got the following versioning issue using poetry to set up my env:

 _Because XXXX (2.0.6 git rev 2.0.6) depends on python-snappy (^0.5.4) which doesn't match any versions, XXXX is forbidden.
  So, because YYYYY depends on XXXX (2.0.6 git rev 2.0.6), version solving failed._

also _pip3 install python-snappy==0.5.4_ fail for me (linux mint). 

Is the older version not maintain? 

Thank you very much for your help!

**Comment by martindurant** [comment]
It is hard to tell from your description what the problem is, or what failure you are facing. At the minimum, please provide your python version, explain what all the X and Ys are about and include the full error message.

The installation instructions on the main page say you must have the binary snappy library installed (`sudo apt-get install libsnappy-dev`); did you do this? Do you have a C compiler chain available?
