### ISSUE TITLE
Snappy.uncompressederror: it’s only possible to uncompress bytes 

### ISSUE THREAD

**Issue by 3980701** [andrix/python-snappy#107]
Hi, 
I have received data in snappy format and need assistance decompressing it. I’ve managed to install snappy and load the snappy file however when I try to decompress it I get the following error. 

Code: 
>>>Import snappy
>>>compressed = open(‘C:\\Users\\pkekesi1\\Technical Assessment_kk\\0.snappy’).read()
>>>snappy.decompose(compressed) 

error: 

snappy.decompressError: it’s only possible to uncompress bytes

**Comment by martindurant** [comment]
The error message tells you you should be passing bytes instead of text/str - open your file in binary mode `open("C:\User...", mode="rb")`.

It's also quite likely that a file (as opposed to a block within a file) is compressed with the *stream* method (aka [framing](https://github.com/google/snappy/blob/master/framing_format.txt)), so maybe replace `decompress` with `stream_decompress` if the above returns an exception about corrupted input.

You will very likely want to do your coding in a real development environment, e.g., jupyter and spyder come included in the anaconda installation. Those would have been more informative about the required arguments for each function, and support autocomplete and such (I note you wrote "decompose" instead of "decompress").
