### ISSUE TITLE
import error on python3.5

### ISSUE THREAD

**Issue by Victor128** [andrix/python-snappy#39]
> > > import snappy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/snappy/**init**.py", line 10, in <module>
> > >     from .SnapPy import (AbelianGroup, HolonomyGroup, FundamentalGroup,
> > >   File "SnapPycore.pxi", line 38, in init SnapPy (cython/SnapPy.c:104679)
> > >   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spherogram/**init**.py", line 3, in <module>
> > >     from .links import \* 
> > >   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spherogram/links/**init**.py", line 1, in <module>
> > >     from .links import Crossing, Strand, Link
> > >   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spherogram/links/links.py", line 2, in <module>
> > >     from .invariants import Link  
> > >   File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/spherogram/links/invariants.py", line 399
> > >     raise ValueError, 'The link diagram is split.'
> > >                     ^
> > > SyntaxError: invalid syntax

**Comment by gpshead** [comment]
that error appears to be due to other libraries, not this snappy library.

You appear to be on a system with a case insensitive filesystem (Mac OS?) and maybe have both this snappy library installed as well as http://www.math.uic.edu/t3m/SnapPy/?

That is not possible without renaming one of them due to the case insensitive name conflict.
