### ISSUE TITLE
python-snappy in windows grabs all memory until dask worker fails

### ISSUE THREAD

**Issue by littlegreenbean33** [andrix/python-snappy#57]
Hi,

I have been chasing a problem over the last days that I initially thought belonged to dask-distributed, later to fastparquet and  eventually to snappy.

What I am doing is very simple. I am taking the larger file of kaggle/wsdm, feeding into  a python script that converts in to parquet.
`
fp.write(os.path.join(parquet_dir,"user_logs.parq"),
                       df,
                       compression="snappy",
                       write_index=True,
                       fixed_text={"msno":44},
                       file_scheme="hive",
                       row_group_offsets=100000,
                       append=True
                      
                      )
`

Essentially a 33GB ascii csv, that once in parquet is about 10GB.

The process is done on linux/ubuntu
dask-workers  in linux ingest it happily.

However, same file in windows with identical spec windows 7 prof fully patched fails. 

Same python lib versions as well
`
distributed.worker - WARNING -  Compute Failed
Function:  _read_parquet_row_group
args:      (<dask.bytes.core.OpenFileCreator object at 0x000000000A876828>, '/home/julian/wsdm/parquet/user_logs.parq/part.2707.parq
uet', 'msno', 'num_100', <class 'fastparquet.parquet_thrift.parquet.ttypes.RowGroup'>
columns: [<class 'fastparquet.parquet_thrift.parquet.ttypes.ColumnChunk'>
file_offset: 1258524
file_path: part.2707.parquet
meta_data: <class 'fastparquet.parquet_thrift.parquet.ttypes.ColumnMetaData'>
  codec: 1
  data_page_offset: 4
  dictionary_page_offset: None
  encoding_stats: [<class 'fastparquet.parquet_thrift.parquet.ttypes.PageEncodingStats'>
count: 1
encoding: 0
page_type: 0
]
  encodings: [3, 4, 0]
  index_page_offset: None
  key_value_metadata: []
  num_values: 100000
  path_in_schema: ['msno']
  statistics: <class 'fastparquet.parquet_thrift.parquet.ttypes.Statistics'>
    distinct_count: None
    max: b'zzqmzWghWZupF3neoC+fNKRkzN6l0BpmRjR1ZUpWnIE='
    min: b'++9nzvvMyez1LasLEYdlEA/toFCTbLhhK6NVozPiQOg='
    null_count: 0

  total_compressed_size: 1258520
  total_unco
kwargs:    {}
Exception: MemoryError()

`

**Comment by andrix** [comment]
@littlegreenbean33 it shouldn't be a `python-snappy` issue, but the way that Parquet is reading the data and using the memory, I believe. 

If you try to decompress something that won't fit your memory, the caller had to find a way to it properly. 

I would raise the issue with the Parquet library developers instead. 

Hope this helps.

**Comment by martindurant** [comment]
User suggests that this is happening during writing, i.e., when you compress rather than decompress, so it *might* be something that belongs to snappy. However, this is apparently an append operation, which involved reading metadata, and the function given is _read_parquet_row_group, which is not actually called by append/write - so all bets are off, I'd say we need more information.

**Comment by littlegreenbean33** [comment]
@andrix @martindurant  This happens at de-compresion. I am just showing how the file was generated. 

Unfortunately  I failed to explain that later.

I simply run a df.column_name.sum().compute() and *only* in windows the worker fails. The linux workers digest the file without problems with same spec machines.

**Comment by martindurant** [comment]
Thanks for the extra information. Since this is dask, it would be helpful to know which scheduler you are using and how many processes/threads. If it really is a snappy problem (as opposed to simply too many workers all trying to claim memory at the same time), then the most likely culprit would be inter-thread disruption.

**Comment by littlegreenbean33** [comment]
@martindurant  I am using distributed.  After many tests I eventually stick to default, that is 1 proc and 8/4 threads depending on core i7/i5 as a standard.  I am running this on four laptops  with 8Gig each on gigabit network. 2 Linux/2win7 machines

Cheers

**Comment by martindurant** [comment]
Interesting to mix linux and win on a cluster...
@andrix , is thread-safety guaranteed on windows?

**Comment by littlegreenbean33** [comment]
@martindurant  well... the mix is just what I happen to have at home these days. A mix of work/corporate and personal computers :-) opens the opportunity of some interesting learning.

**Comment by andrix** [comment]
@martindurant that's a good question that I don't know. I'm not a windows user, the test I did when I've started where on an old windows 7 machine. I don't have a windows machine to test this, unfortunately, but we should.

But the library, release the GIL during compress or decompress (https://github.com/andrix/python-snappy/blob/master/snappy/snappymodule.cc#L114) so if there is other threads executing they may, and the buffer is not locked.

I don't know how the implementation of dask works, we'll need to see it. As you suggested above, we'll need more information to see where is happening the error. Snappy is simple enough, and I'm leaning to say the error is because a condition the caller is not enforcing. Although, is interesting that in Linux works and it fails on Windows ...

**Comment by martindurant** [comment]
@littlegreenbean33 , I would suggest for now that you use fewer workers and threads on the windows machines. It seems generally true that (python on) windows is worse at releasing memory, worse at handling virtual memory and worse at buffering when multiple processes access the disc at the same time. You might be being hit by one of these effects.

**Comment by littlegreenbean33** [comment]
@martindurant I run a full set of tests... overnight, on windows and linux. @andrix  is right that it is not a snappy problem. Just a reflection of exhaustion of memory.

Just for your records this are the tests I did

1. parquet file with hive format and snappy compression default row_group_offsets. ddf.count().compute()

- Windows
-- dask threading OK.  50% memory usage
-- dask multiprocession OK  50% memory usage
-- dask distributed locally (c=Client()) OK, much more memory greedy but finalizes

- Linux
--- dask threading OK. Extremely memory greed but no swapping. 
--- dask multiprocessing OK. Extremely memory greed. Tons of swapping.  Eventually finished without blowing away.
--- dask distributed local (c=Client())  FAIL. Blows after exausting memory.

2. parquet file with hive format and snappy compression  row_group_offsets=100.000  ddf.count().compute()
- Windows
-- dask threading OK.  negligible memory usage ( as expected) 
-- dask multiprocession OK  negligible memory usage ( as expected) 
-- dask distributed locally (c=Client()) OK, 50% memory usage

- Linux
--- dask threading OK. negligible memory usage ( as expected) 
--- dask multiprocessing OK. small footprint. Fast !
--- dask distributed local (c=Client())  FAIL. Blows after exhausting memory.
--- dask distributed non local (c=Client("192.168.1.33:8786") Blows away.

I can only conclude from  these tests that there is a problem in dask.distributed. I will repost this in their project.

@martindurant  contrary to your ( and mine) expectations Windows implementation does a fantastic job releasing memory.....
